area/agent:
  - changed-files:
      - any-glob-to-any-file:
          - 'cmd/agent/**'
          - 'pkg/agent/**'
          - 'internal/agent/**'

area/controller:
  - changed-files:
      - any-glob-to-any-file:
          - 'cmd/controller/**'

area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.golangci.yml'

area/test:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**'
          - '**/*_test.go'

area/probe:
  - changed-files:
      - any-glob-to-any-file:
          - 'pkg/probes/**'
  