area/agent:
  any:
    - changed-files:
        - cmd/agent/**
        - pkg/agent/**

area/ci:
  any:
    - changed-files:
        - .github/**

area/test:
  any:
    - changed-files:
        - test/**
        - '**/*_test.go'

area/probe:
  any:
    - changed-files:
        - pkg/probes/**
