area/agent:
  - changed-files:
    - any-glob-to-any-file:
      - 'cmd/agent/**'
      - 'pkg/agent/**'

area/ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'

area/test:
  - changed-files:
    - any-glob-to-any-file:
      - 'test/**'
      - '**/*_test.go'

area/probe:
  - changed-files:
    - any-glob-to-any-file:
      - 'pkg/probes/**'
