area/agent:
- change-files:
  - any-glob-to-any-file:
    - cmd/agent/**
    - pkg/agent/**

area/ci:
- change-files:
  - any-glob-to-any-file:
    - .github/**

area/test:
- change-files:
  - any-glob-to-any-file:
    - test/**
    - '**/*_test.go'

area/probe:
- change-files:
  - any-glob-to-any-file:
    - pkg/probes/**
