area/agent:
- any:
  - changed-files:
    - cmd/agent/**
    - pkg/agent/**

area/ci:
- any:
  - changed-files:
  - any-glob-to-any-file:
    - .github/**

area/test:
- any:
  - changed-files:
  - any-glob-to-any-file:
    - test/**
    - '**/*_test.go'

area/probe:
- any:
  - changed-files:
  - any-glob-to-any-file:
    - pkg/probes/**
