area/agent:
  - changed-files:
    - 'cmd/agent/**'
    - 'pkg/agent/**'

area/ci:
  - changed-files:
    - '.github/**'

area/test:
  - changed-files:
    - 'test/**'
    - '**/*_test.go'

area/probe:
  - changed-files:
    - 'pkg/probes/**'
