version: "2"

run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable:
      - shadow

linters:
  disable-all: true
  enable:
    - errcheck # check for unchecked errors
    - govet # check for common mistakes
    - staticcheck # check for static errors
    - unused # check for unused variables
    - ineffassign # check for inefficient assignments
    - revive # check for code smells

issues:
  exclude-dirs:
    - bin
    - headers
  
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_bpfel\\.go$"
    - ".*_bpfeb\\.go$"
    - ".*\\.o$"
  
  exclude-rules:    
    - path: _test\.go
      linters:
        - errcheck
        - unused
  
  max-issues-per-linter: 0
  max-same-issues: 0
