run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - headers
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_bpfel\\.go$"
    - ".*_bpfeb\\.go$"
    - ".*\\.o$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable:
      - shadow

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
  
  max-issues-per-linter: 0
  max-same-issues: 0
