// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/bpfstack.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryEvent is a event that is sent from the agent to the controller.
type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ProbeName     string                 `protobuf:"bytes,2,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`           // JSON encoded data.
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in nanoseconds.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_api_proto_v1_bpfstack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_bpfstack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_bpfstack_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryEvent) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *TelemetryEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TelemetryEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Command is a command that is sent from the controller to the agent.
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProbeName string                 `protobuf:"bytes,1,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	// Enable or disable the probe.
	Enabled       bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_v1_bpfstack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_bpfstack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_bpfstack_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *Command) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_api_proto_v1_bpfstack_proto protoreflect.FileDescriptor

const file_api_proto_v1_bpfstack_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/bpfstack.proto\x12\x02v1\"|\n" +
	"\x0eTelemetryEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x02 \x01(\tR\tprobeName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"B\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x01 \x01(\tR\tprobeName\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled2@\n" +
	"\bBpfstack\x124\n" +
	"\rStreamConnect\x12\x12.v1.TelemetryEvent\x1a\v.v1.Command(\x010\x01B%Z#github.com/bpfstack/bpfstack/api/v1b\x06proto3"

var (
	file_api_proto_v1_bpfstack_proto_rawDescOnce sync.Once
	file_api_proto_v1_bpfstack_proto_rawDescData []byte
)

func file_api_proto_v1_bpfstack_proto_rawDescGZIP() []byte {
	file_api_proto_v1_bpfstack_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_bpfstack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_bpfstack_proto_rawDesc), len(file_api_proto_v1_bpfstack_proto_rawDesc)))
	})
	return file_api_proto_v1_bpfstack_proto_rawDescData
}

var file_api_proto_v1_bpfstack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_bpfstack_proto_goTypes = []any{
	(*TelemetryEvent)(nil), // 0: v1.TelemetryEvent
	(*Command)(nil),        // 1: v1.Command
}
var file_api_proto_v1_bpfstack_proto_depIdxs = []int32{
	0, // 0: v1.Bpfstack.StreamConnect:input_type -> v1.TelemetryEvent
	1, // 1: v1.Bpfstack.StreamConnect:output_type -> v1.Command
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_bpfstack_proto_init() }
func file_api_proto_v1_bpfstack_proto_init() {
	if File_api_proto_v1_bpfstack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_bpfstack_proto_rawDesc), len(file_api_proto_v1_bpfstack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_bpfstack_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_bpfstack_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_bpfstack_proto_msgTypes,
	}.Build()
	File_api_proto_v1_bpfstack_proto = out.File
	file_api_proto_v1_bpfstack_proto_goTypes = nil
	file_api_proto_v1_bpfstack_proto_depIdxs = nil
}
