// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/v1/bpfstack.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bpfstack_StreamConnect_FullMethodName = "/v1.Bpfstack/StreamConnect"
)

// BpfstackClient is the client API for Bpfstack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bpfstack is the service that allows the agent to connect to the controller.
type BpfstackClient interface {
	// Bidirectional stream of telemetry events.
	StreamConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryEvent, Command], error)
}

type bpfstackClient struct {
	cc grpc.ClientConnInterface
}

func NewBpfstackClient(cc grpc.ClientConnInterface) BpfstackClient {
	return &bpfstackClient{cc}
}

func (c *bpfstackClient) StreamConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryEvent, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bpfstack_ServiceDesc.Streams[0], Bpfstack_StreamConnect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryEvent, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bpfstack_StreamConnectClient = grpc.BidiStreamingClient[TelemetryEvent, Command]

// BpfstackServer is the server API for Bpfstack service.
// All implementations must embed UnimplementedBpfstackServer
// for forward compatibility.
//
// Bpfstack is the service that allows the agent to connect to the controller.
type BpfstackServer interface {
	// Bidirectional stream of telemetry events.
	StreamConnect(grpc.BidiStreamingServer[TelemetryEvent, Command]) error
	mustEmbedUnimplementedBpfstackServer()
}

// UnimplementedBpfstackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBpfstackServer struct{}

func (UnimplementedBpfstackServer) StreamConnect(grpc.BidiStreamingServer[TelemetryEvent, Command]) error {
	return status.Error(codes.Unimplemented, "method StreamConnect not implemented")
}
func (UnimplementedBpfstackServer) mustEmbedUnimplementedBpfstackServer() {}
func (UnimplementedBpfstackServer) testEmbeddedByValue()                  {}

// UnsafeBpfstackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BpfstackServer will
// result in compilation errors.
type UnsafeBpfstackServer interface {
	mustEmbedUnimplementedBpfstackServer()
}

func RegisterBpfstackServer(s grpc.ServiceRegistrar, srv BpfstackServer) {
	// If the following call panics, it indicates UnimplementedBpfstackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bpfstack_ServiceDesc, srv)
}

func _Bpfstack_StreamConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BpfstackServer).StreamConnect(&grpc.GenericServerStream[TelemetryEvent, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bpfstack_StreamConnectServer = grpc.BidiStreamingServer[TelemetryEvent, Command]

// Bpfstack_ServiceDesc is the grpc.ServiceDesc for Bpfstack service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bpfstack_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Bpfstack",
	HandlerType: (*BpfstackServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConnect",
			Handler:       _Bpfstack_StreamConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/bpfstack.proto",
}
